"""empty message

Revision ID: 585083de4dc6
Revises: 9fd865ee0078
Create Date: 2022-02-21 16:36:31.394518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '585083de4dc6'
down_revision = '9fd865ee0078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('court', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('court', 'time')
    # ### end Alembic commands ###
