"""empty message

Revision ID: 94e85ce79106
Revises: f216b0d4ee1f
Create Date: 2022-02-07 22:00:43.986969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e85ce79106'
down_revision = 'f216b0d4ee1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('zip_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'zip_code')
    # ### end Alembic commands ###
