"""empty message

Revision ID: 9fd865ee0078
Revises: 94e85ce79106
Create Date: 2022-02-08 10:55:57.484329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd865ee0078'
down_revision = '94e85ce79106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('court', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'court', 'location', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'court', type_='foreignkey')
    op.drop_column('court', 'location_id')
    # ### end Alembic commands ###
