"""empty message

Revision ID: b50366ced5c3
Revises: c62f6c5fbd4a
Create Date: 2022-02-21 16:41:07.225830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b50366ced5c3'
down_revision = 'c62f6c5fbd4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('court', 'time')
    op.add_column('court_status', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('court_status', 'time')
    op.add_column('court', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
