"""empty message

Revision ID: f216b0d4ee1f
Revises: 0ea9d2d6d193
Create Date: 2022-02-07 21:58:38.653602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f216b0d4ee1f'
down_revision = '0ea9d2d6d193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'name')
    # ### end Alembic commands ###
